### ISSUE TITLE
Project Infinity install order problem

### ISSUE THREAD

**Issue by Communard1871** [lzenner/framed#1]
There is a strange issue with this mod when using Project Infinity - BG1 NPC project requires itself to be installed after Framed, while Framed requires itself to be installed after BG1 NPC - paradox!

This does not permit installation to ever continue with both these mods selected.

**Comment by TeskalFlink** [comment]
Check the readme's of these mods, they will tell which need to be loaded first and after which mod. Open their ini's and remove the wrong entry.
